### ISSUE TITLE
Annotation `rootly.com/app-name` value is being ignored

### ISSUE THREAD

**Issue by drankou** [rootlyhq/backstage-plugin#6]
When specifying `rootly.com/app-name` value for the service, `RootlyOverviewCard` component ignores it and takes the [entity triplet](https://github.com/rootlyhq/backstage-plugin/blob/34b4b30b925c6c6b993accc9e1936d756b7f3bde/src/components/Entity/RootlyOverviewCard.tsx#L116) from the entity page for [the following API call to Rootly.](https://github.com/rootlyhq/backstage-plugin/blob/34b4b30b925c6c6b993accc9e1936d756b7f3bde/src/components/Entity/RootlyOverviewCard.tsx#L130)

Therefore the annotation itself acts like a true/false for component rendering when used with `isRootlyAvailable` condition, rather than be an instruction of which app info should be rendered.

**Comment by kwent** [comment]
Added annotations support in 0.3.2 with https://github.com/rootlyhq/backstage-plugin/commit/d4aea3d2e0b9def20e27543ff167bda390521693. Give it a try !

### Annotations

Available annotations are the following:

```yaml
rootly.com/service-id: 7a328a08-6701-445e-a1ad-ca2fb913ed1e # Use service-id or service-slug. Not both.
rootly.com/service-slug: elasticsearch-staging # Use service-id or service-slug. Not both.
rootly.com/service-auto-import: enabled # This will auto import the entity as a rootly service if we don't find any.
```

#### Example

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch-staging
  description: |
   elasticsearch-staging
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://rootly.com
    rootly.com/service-slug: elasticsearch-staging
    rootly.com/service-auto-import: enabled
spec:
  type: grpc
  owner: guests
  lifecycle: experimental
```
